PROTZILLA_COLOR_SEQUENCE = [
    "#4A536A",
    "#87A8B9",
    "#CE5A5A",
    "#8E3325",
    "#E2A46D",
]
PROTZILLA_PRIMARY_COLOR = PROTZILLA_COLOR_SEQUENCE[0]
PROTZILLA_SECONDARY_COLOR = PROTZILLA_COLOR_SEQUENCE[2]