from colour import color_scale
from docutils.nodes import title
from tqdm import tqdm
from protzilla.constants.paths import EXTERNAL_DATA_PATH
from protzilla.data_analysis.differential_expression_mann_whitney import (
    mann_whitney_test_on_intensity_data,
)
from protzilla.disk_operator import PickleOperator
from protzilla.constants.colors import (
    PLOT_PRIMARY_COLOR,
    PLOT_COLOR_SEQUENCE,
    interpolate_color,
)
from dataclasses import dataclass
import pandas as pd
from numpy import log2
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from protzilla.constants.protzilla_logging import logger

# import StrEnum
from enum import StrEnum

INTENSITY_COLORS = ["#FFFFFF", PLOT_COLOR_SEQUENCE[3]]
SEQUENCE_DEPTH_PEPTIDE_SPACING = 1


class IntensityNormalization(StrEnum):
    min_max_scaling = "min_max_scaling"
    none = "none"


class AggregationMethod(StrEnum):
    median = "median"
    mean = "mean"


@dataclass(unsafe_hash=True)
class PeptideMatch:
    peptide_sequence: str
    start_location_on_protein: int
    end_location_on_protein: int
    intensity: float = 0.0
    metadata_group: str = ""


@dataclass(unsafe_hash=True)
class ProteinHit:
    protein_id: str
    start_location_on_protein: int
    end_location_on_protein: int


class IntensityNormalization(StrEnum):
    min_max_scaling = "min_max_scaling"
    none = "none"


def build_kmer_dictionary(
    protein_dictionary: dict[str, str], k: int = 5
) -> dict[str, list[tuple[str, int]]]:
    """
    Builds a dictionary of all kmers in a list of protein sequences. The kmers are generated by sliding a window of size
    k along the protein sequences. The dictionary maps a the k-mer to a list of tuples containing the protein ID and
    the index of
    the k-mer in the protein sequence. The dictionary is saved to disk for future use.
    """
    # if the dictionary already exists, load it from disk
    kmer_dict_path = EXTERNAL_DATA_PATH / f"kmer_dict_{k}.pkl"
    if kmer_dict_path.exists():
        kmer_dict = PickleOperator.read(kmer_dict_path)
        return kmer_dict
    kmer_dict = {}
    for protein_id, protein_sequence in tqdm(
        protein_dictionary.items(),
        desc="Building kmer dictionary",
        unit_scale=True,
        unit="protein",
    ):
        for i in range(len(protein_sequence) - k + 1):
            kmer = protein_sequence[i : i + k]
            if kmer in kmer_dict:
                kmer_dict[kmer].append((protein_id, i))
            else:
                kmer_dict[kmer] = [(protein_id, i)]
    PickleOperator.write(kmer_dict_path, kmer_dict)
    return kmer_dict


def match_peptide_to_protein_ids(
    peptide_sequence: str,
    protein_kmer_dictionary: dict[str, list[tuple[str, int]]],
    protein_dictionary: dict[str, str],
) -> list[ProteinHit]:
    """
    Matches a peptide sequence to a dictionary of kmers in protein sequences.
    Returns a list of tuples containing the protein ID and the start, end location of the peptide in the protein
    sequence.
    """
    if len(peptide_sequence) == 0:
        raise ValueError("Peptide sequence is empty.")
    k = 5
    peptide_kmers = [
        peptide_sequence[i : i + k] for i in range(len(peptide_sequence) - k + 1)
    ]
    first_kmer, last_kmer = peptide_kmers[0], peptide_kmers[-1]
    # match the kmers
    first_kmer_matches = protein_kmer_dictionary.get(first_kmer, [])
    last_kmer_matches = protein_kmer_dictionary.get(last_kmer, [])
    hits = [
        ProteinHit(
            protein_id, start_first_kmer, start_first_kmer + len(peptide_sequence)
        )
        for protein_id, start_first_kmer in first_kmer_matches
        for _, start_last_kmer in last_kmer_matches
        if protein_id == _
        and start_last_kmer == start_first_kmer + len(peptide_sequence) - k
        and protein_dictionary[protein_id][
            start_first_kmer : start_first_kmer + len(peptide_sequence)
        ]
        == peptide_sequence
    ]
    hits = list(set(hits))  # remove duplicates

    # Just sanity checks
    for hit in hits:
        subsequence = protein_dictionary[hit.protein_id][
            hit.start_location_on_protein : hit.end_location_on_protein
        ]
        assert len(subsequence) == len(
            peptide_sequence
        ), f"Lengths do not match: {len(subsequence)} != {len(peptide_sequence)}"
        assert subsequence in peptide_sequence, (
            f"Subsequence not in peptide sequence:\nA: {subsequence}\nB: "
            f"{peptide_sequence}"
        )
        assert peptide_sequence in protein_dictionary[hit.protein_id], (
            f"Peptide not in protein sequence: {peptide_sequence} not in "
            f"{protein_dictionary[protein_id]}"
        )
    return hits


def plot_protein_coverage(
    fasta_df: pd.DataFrame,
    peptide_df: pd.DataFrame,
    metadata_df: pd.DataFrame,
    protein_id: str,
    grouping: str,
    selected_groups: list[str] = None,
    aggregation_method: AggregationMethod = AggregationMethod.median,
) -> None:
    """
    Plots the coverage of a protein sequence by peptides.
    """
    # generate the protein kmer dictionary
    if selected_groups is None or selected_groups == []:
        raise ValueError("No samples provided.")

    # add group information to the peptide dataframe
    peptide_df = peptide_df.merge(metadata_df, on="Sample")

    reduced_peptide_df = peptide_df[
        peptide_df[grouping].isin(selected_groups) & peptide_df["Intensity"] > 0
    ]
    if len(reduced_peptide_df) == 0:
        raise ValueError("No peptides found for the samples provided.")

    protein_sequence_dict = dict(
        zip(fasta_df["Protein ID"], fasta_df["Protein Sequence"])
    )
    sequence_kmer_dict = build_kmer_dictionary(protein_sequence_dict, k=5)

    protein_sequence = protein_sequence_dict[protein_id]
    peptide_matches = []
    coverage_by_group_name = {
        sample: [0] * len(protein_sequence) for sample in selected_groups
    }

    for (group_name, peptide_sequence), row in tqdm(
        reduced_peptide_df[[grouping, "Sequence", "Intensity"]]
        .drop_duplicates()
        .groupby([grouping, "Sequence"]),
        desc="Matching peptides to protein",
        unit_scale=True,
        unit="peptide",
    ):
        sample = extract_peptide_from_slice(row, aggregation_method)
        if sample.empty:
            continue
        intensity = sample["Intensity"].values[0]
        protein_hits = match_peptide_to_protein_ids(
            peptide_sequence=peptide_sequence,
            protein_kmer_dictionary=sequence_kmer_dict,
            protein_dictionary=protein_sequence_dict,
        )
        # we only care about the hits pertaining to the argument-supplied protein id
        filtered_protein_hits = filter(
            lambda x: x.protein_id == protein_id, protein_hits
        )
        for protein_hit in filtered_protein_hits:
            # add the peptide sequence and location to the peptide matches pertaining to the protein id
            peptide_matches.append(
                PeptideMatch(
                    peptide_sequence=peptide_sequence,
                    start_location_on_protein=protein_hit.start_location_on_protein,
                    end_location_on_protein=protein_hit.end_location_on_protein,
                    intensity=log2(intensity),
                    metadata_group=group_name,
                )
            )
            # update the coverage of the protein sequence
            increment_coverage(coverage_by_group_name[group_name], protein_hit)

    if len(peptide_matches) == 0:
        raise ValueError(f"No peptides matched for protein {protein_id}")

    # now that all the matches have been determined with their start and end on the protein sequence, we need to find
    # an optimal solution for the location of their rectangles in the plot without overlap while minimizing the
    # required number of rows (vertical space)
    rows_by_group_name = distribute_to_rows(peptide_matches)

    fig = build_coverage_plot(
        coverages_by_group_name=coverage_by_group_name,
        peptide_matches=peptide_matches,
        protein_id=protein_id,
        protein_sequence=protein_sequence,
        rows_by_group_name=rows_by_group_name,
        grouping=grouping,
    )

    return dict(plots=[fig])


def build_coverage_plot(
    coverages_by_group_name: list[int],
    peptide_matches: list[PeptideMatch],
    protein_id: str,
    protein_sequence: str,
    rows_by_group_name: dict[str, list[list[PeptideMatch]]],
    intensity_normalization: IntensityNormalization = IntensityNormalization.min_max_scaling,
    grouping: str = "",
) -> go.Figure:
    number_of_subplots = len(rows_by_group_name.keys())
    protein_sequence_labels = [
        f"{amino_acid} - {amino_acid_index} "
        for amino_acid_index, amino_acid in enumerate(protein_sequence)
    ]
    subplot_titles = [
        f"Peptides of {group_name}" for group_name in rows_by_group_name.keys()
    ]
    max_coverage_value = get_max_coverage(coverages_by_group_name)

    fig = make_subplots(
        rows=number_of_subplots,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.1,
        subplot_titles=subplot_titles,
        specs=[[{"secondary_y": True}] for _ in range(number_of_subplots)],
    )
    # Peptides
    for group_index, group_name in enumerate(rows_by_group_name.keys(), start=1):
        peptide_rows = rows_by_group_name[group_name]
        coverage = coverages_by_group_name[group_name]

        add_sequence_depth_to_plot(
            fig=fig,
            coverage=coverage,
            group_subplot_index=group_index,
            protein_sequence_labels=protein_sequence_labels,
        )

        # Peptide plot
        current_group_intensities = [
            peptide_match.intensity for row in peptide_rows for peptide_match in row
        ]
        max_intensity, min_intensity = max(current_group_intensities), min(
            current_group_intensities
        )
        scale_intensity = lambda intensity: (intensity - min_intensity) / (
            max_intensity - min_intensity
        )
        for row_index, row in enumerate(peptide_rows):
            for peptide_match in row:
                add_peptide_to_plot(
                    fig=fig,
                    normalized_intensity=scale_intensity(peptide_match.intensity),
                    peptide_match=peptide_match,
                    group_subplot_index=group_index,
                    protein_sequence_labels=protein_sequence_labels,
                    row_index=row_index,
                    offset=max_coverage_value + SEQUENCE_DEPTH_PEPTIDE_SPACING,
                    color_a=INTENSITY_COLORS[0],
                    color_b=INTENSITY_COLORS[1],
                    grouping=grouping,
                )

        fig.update_layout(hovermode="closest")
        fig.update_yaxes(
            range=[
                0,
                len(peptide_rows) + max_coverage_value + SEQUENCE_DEPTH_PEPTIDE_SPACING,
            ],
            showticklabels=False,
            showgrid=False,
            row=group_index,
            col=1,
        )
        fig.update_xaxes(showticklabels=False, showgrid=False, row=group_index, col=1)
    fig.update_xaxes(showticklabels=True, row=number_of_subplots, col=1)

    add_intensity_legend(fig)

    return fig


def add_intensity_legend(fig):
    color_scale = [[0, INTENSITY_COLORS[0]], [1, INTENSITY_COLORS[1]]]
    color_legend_trace = go.Scatter(
        x=[None],
        y=[None],
        mode="markers",
        marker=dict(
            colorscale=color_scale,
            showscale=True,
            cmin=0,
            cmax=1,
            colorbar=dict(
                title="Intensity of peptide",
                x=1.0,  # Move further outside the plot
                len=0.9,  # Increase length of colorbar (70% of subplot height)
                thickness=30,  # Increase thickness of colorbar
                titleside="right",  # Move title to the right side of the bar
            ),
            size=10,
        ),
        showlegend=False,
    )
    fig.add_trace(color_legend_trace, row=1, col=1)


def add_sequence_depth_to_plot(
    fig: go.Figure,
    coverage: list[int],
    group_subplot_index: int,
    protein_sequence_labels: list[str],
) -> None:
    SEQUENCE_DEPTH_BAR_CHART = dict(
        x=protein_sequence_labels,
        y=coverage,
        showlegend=False,
        marker=dict(color=PLOT_PRIMARY_COLOR),
        # add hover text
        hoverinfo="y",
        hovertemplate="Sequencing depth at %{x}: %{y}",
    )
    fig.add_trace(go.Bar(**SEQUENCE_DEPTH_BAR_CHART), row=group_subplot_index, col=1)


def add_peptide_to_plot(
    fig: go.Figure,
    normalized_intensity: float,
    peptide_match: PeptideMatch,
    group_subplot_index: int,
    protein_sequence_labels: list[str],
    row_index: int,
    offset: int,
    color_a: str = "#FFFFFF",
    color_b: str = PLOT_COLOR_SEQUENCE[3],
    grouping: str = "",
) -> None:
    x0, x1 = (
        peptide_match.start_location_on_protein,
        peptide_match.end_location_on_protein,
    )
    y0, y1 = row_index + offset, row_index + offset + 1
    # interpolate between the two colors
    color = interpolate_color(color_a, color_b, normalized_intensity)
    PEPTIDE_SHAPE = dict(
        type="rect",
        x0=x0 - 0.5,
        y0=y0,
        x1=x1 - 0.5,
        y1=y1,
        fillcolor=color,
        line_color=color,
        layer="above",
    )
    fig.add_shape(**PEPTIDE_SHAPE, row=group_subplot_index, col=1)
    # add invisible plotly object to the rectangle to show the peptide sequence when hovered over
    fig.add_trace(
        go.Scatter(
            x=protein_sequence_labels[
                peptide_match.start_location_on_protein : peptide_match.end_location_on_protein
                + 1
            ],
            y=[(y0 + y1) / 2] * len(peptide_match.peptide_sequence),
            text=[
                f"{grouping}: {peptide_match.metadata_group}<br>Peptide: {peptide_match.peptide_sequence}<br>"
                f"({peptide_match.start_location_on_protein}-{peptide_match.end_location_on_protein})<br>"
                f"Intensity: {peptide_match.intensity}"
            ]
            * len(peptide_match.peptide_sequence),
            mode="markers",
            marker=dict(opacity=0, size=15),  # make marker invisible
            hoverinfo="text",
            hovertemplate="%{text}<extra></extra>",
            showlegend=False,
        ),
        row=group_subplot_index,
        col=1,
    )


def increment_coverage(coverage: list[int], protein_hit: ProteinHit) -> None:
    coverage[
        protein_hit.start_location_on_protein : protein_hit.end_location_on_protein
    ] = [
        coverage + 1
        for coverage in coverage[
            protein_hit.start_location_on_protein : protein_hit.end_location_on_protein
        ]
    ]


def extract_peptide_from_slice(
    slice_df: pd.DataFrame,
    aggregation_strategy: AggregationMethod = AggregationMethod.median,
) -> pd.DataFrame:
    """
    Given multiple peptide datapoints, return a single peptide datapoint with the intensity value extracted from the
    slice of the peptide data.
    """
    if len(slice_df) == 1:
        return slice_df
    if aggregation_strategy == AggregationMethod.median:
        slice_df = slice_df.groupby("Sequence").median()
    elif aggregation_strategy == AggregationMethod.mean:
        slice_df = slice_df.groupby("Sequence").mean()
    else:
        raise ValueError(f"Unknown strategy: {aggregation_strategy}")
    return slice_df


def distribute_to_rows(
    peptide_matches: list[PeptideMatch],
) -> dict[list[list[PeptideMatch]]]:
    """
    Distributes peptide matches to rows such that no two peptides overlap in the same row.
    Greedy algorithm (see Interval Scheduling Problem).
    """
    peptide_matches.sort(
        key=lambda peptide_match: peptide_match.start_location_on_protein
    )
    rows = {
        group_name: []
        for group_name in set(
            [peptide_match.metadata_group for peptide_match in peptide_matches]
        )
    }
    for peptide_match in peptide_matches:
        # find the first row that does not overlap with the current peptide
        for row in rows[peptide_match.metadata_group]:
            if (
                row[-1].end_location_on_protein
                < peptide_match.start_location_on_protein
            ):
                row.append((peptide_match))
                break
        else:
            rows[peptide_match.metadata_group].append([(peptide_match)])
    return rows


def get_max_coverage(coverage: dict[list[int]]) -> int:
    return max([max(coverage) for coverage in coverage.values()])
